#端口
server:
  port: 8080

#spring的配置
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  #数据源的配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://115.159.69.180/testManage?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: testManage
    password: lutingwang
    #注入数据源的类型   默认的为HikariDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-active: 20
      min-idle: 5
      validation-query: select x
      initial-size: 3
      max-wait: 5000
      stat-view-servlet:
        #        login-username: root
        #        login-password: 123456
        allow:
        deny:
        url-pattern: /druid/*
        enabled: true  #启用数据源监控
  #配置redis
  redis:
    port: 6390
    host: 115.159.69.180   #116.45.1.15
    password: 123456
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

#shiro配置
shiro:
  anon-urls:
    - /login/doLogin*
    - /login/captcha*
    - /login/logout*
    - /druid/**
    - /pay/callback/**
  authc-urls:
    - /**
#mybatisplus的配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*Mapper.xml
  global-config:
    db-config:
      id-type: auto
#fastdfs的配置
fdfs:
  so-timeout: 25000       # 读取时间
  connect-timeout: 6000   # 连接超时时间
  thumb-image:           # 缩略图
    width: 100
    height: 100
  tracker-list:          # tracker服务配置地址列表
    - 115.159.69.180:22122
upload:
  base-url: http://115.159.69.180:8848
  allow-types:
    - image/jpeg
    - image/png
    - image/bmp
    - image/gif
    - image/jpg
    - audio/mpeg
    - audio/flac
    - audio/mp3
    - application/vnd.ms-excel
#dubbo配置

dubbo:
  application:
    name: test-system-web-service
  registry:
    address: zookeeper://localhost:2181
  protocol:
    name: dubbo
    port: -1
  consumer:
    check: false
    timeout: 30000
  config-center:
    timeout: 100000

